### ISSUE TITLE
Template coordinate offset multiplier

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-GUI-V2#266]
This is a request from Zaspar.

### Idea
The idea is that you have segment you want repeated at X+a, X+2a & X+3a.
Currently you would type in offset a and then 2a and then 3a. Which is a bit cumbersome.
For instance you would have to type in 4, 8, & 12

So it would be preferable if there was an offset multiplier that could **auto-increment**. This counter could be contained in a new integer box.

### UI
The UI of Templates is getting a bit cluttered. Maybe we need a new row of controls or something similar.

**Comment by MortenTobiasNielsen** [comment]
This would be really nice to have. I have also multiple times found myself doing this 10+ times, which is doable but would be nice that it was automatic.

Agreed. The UI would needs some sort of overhaul to be able to contain more functionality.

**Comment by theis999** [comment]
If we are looking at an overhaul, we might as well consider adding rotations and/or mirroring of templates.

**Comment by MortenTobiasNielsen** [comment]
It would for sure be nice to have, it does though sound like it could become really complex. 😅

**Comment by theis999** [comment]
Certainly, but it has been done many times for other applications so it should be doable.

**Comment by MortenTobiasNielsen** [comment]
Agreed it is possible, just difficult. 😀

**Comment by theis999** [comment]
Closed as completed
