### ISSUE TITLE
Choose step type colour

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-GUI-V2#288]
It would be neat to have a way to choose your own custom colours for step types. 

It could be added to the generator-settings file.
The GUI part could be done similar to the change shortcuts.

The immediate goal for me is to colour Walk & Mine. As these are just white, however i often use them as control steps.

**Comment by MortenTobiasNielsen** [comment]
It would be nice if the user was able to customize what they see as being important - I think this would be a valuable addition to the tool. 👍

**Comment by theis999** [comment]
I'll implement something similar to the shortcut changer.
