### ISSUE TITLE
Generate scenario (Release)

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-GUI-V2#290]
I have asked around and the general consensus seems to be, that best approach to release a TAS is through a scenario.

As that should allow for the inclusion of both LUA code and map settings. Making it a cleaner solution to releasing a TAS to the public than including a map-exchange-string.

Implementation:
- It needs a new file path: to the scenarios folder
- It needs a map generation details (lets hope an exchange string works)
- Both can be placed in the **Script** menu

Scenarios are slightly different from mods, but from the description none of the differences should matter to us.

**Comment by MortenTobiasNielsen** [comment]
Sounds like a good idea. I hope it is possible to implement.

**Comment by theis999** [comment]
It turns out that my initial idea for implementing this was vastly more complicated than i anticipated. So I'll postpone this for a little while.
