### ISSUE TITLE
Paint state modifiers based on state

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-GUI-V2#291]
It is a bit hard to gauge if a state modifier (such as keep-walking) is on.

A simple method is to count the number of them, perhaps during script generation, and then paint the modifier green if there is an odd amount of that state among the steps.

**Comment by MortenTobiasNielsen** [comment]
Agreed it is not really obvious, so it would be nice with some kind of indication. It might though be difficult if a step has multiple modifiers and one of them is one and the other is off - for sure an edge case, but might happen.

**Comment by theis999** [comment]
I meant **state** modifiers (the steps that controls **warnings**), not step modifiers. Sorry for the confusion. The other thing is a valid problem too.

The simple solution to visualizing more than two step modifiers is to extend the row to take up more pixels vertically. It may not be pretty. Alternatively we could try to find shorthand names for each modifier (1-6 characters) to make them easier to fit. Either way i don't think it is as important as this issue.

The problem with state modifiers as they are right now. Is that they are fundamentally code blocks, with the potential for overlapping blocks. Which makes them very hard to display in an intuitive way.
