### ISSUE TITLE
Chart map

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-GUI-V2#324]
The map is created as you move to edges of it. This means that different routing options can create slight differences in the final map.

**Comment by MortenTobiasNielsen** [comment]
Can we do anything about that? 🤔

**Comment by theis999** [comment]
The freeplay scenario has this function:
```
set_chart_distance = function(value)
    global.chart_distance = tonumber(value) or error("Remote call parameter to freeplay set chart distance must be a number")
end,
``` 
  
So i assume we can just call it with a value higher than standard. Which i think is 200.

The important question is if we want to "fix" it.

**Comment by MortenTobiasNielsen** [comment]
I don't think we want to fix this, given that it could have unforeseen consequences. Users doesn't really have the ability to change their running patterns in the past anyway without major impact to their run.

**Comment by theis999** [comment]
I think you are correct.
In other news, a new lua functionality has been added with 1.1.89 that allows us to intercept chart map and change the map settings. Which i understand to mean that we can enforce the specific map string regardless of what users input in the new game dialog.

**Comment by MortenTobiasNielsen** [comment]
Sounds like that could be useful. :)
