### ISSUE TITLE
Support for Supply challenge scenario

### ISSUE THREAD

**Issue by seky16** [MortenTobiasNielsen/Factorio-GUI-V2#335]
Hello,

I'm interested in creating TAS for Factorio's Supply challenge scenario.

However there's couple of things that would need to be considered and changed in FTG.

- Apart from slight changes in `control.lua` there is no problem in running FTG generated TAS with the Supply challenge scenario.
- `goals.lua`would need to be extended as well, since Supply challenge features custom win condition.
- The main problem is with advancing through the scenario levels: in RTA you do that by clicking a `mod-gui` button, which is not possible through lua API. There is however a way to workaround this. In FTG there would need to be a new step type "Next level" (similiar to "Launch"). This would call a remote interface that would advance the level in the scenario. HOWEVER such a remote doesn't exist, leading to a three available solutions:
    1. File an official feature request to Factorio devs and have them add such a remote interface (not really that hard, but depends on their will).
    2. Using Factorio's [Instrument mode](https://lua-api.factorio.com/latest/Instrument.html) hijack the scenario's `control.lua` and add the remote ourselves. See code below, this would be an extra lua file `instrument-control.lua` that would need to be a part of the generated mod. Then the game needs to be run with the command line argument `--instrument-mod modname`, which is not ideal. It also disables multiplayer, which only affects the Supply challenge scenario in a way that in SP it shows extra messages at the start that need to be manually skipped.
    3. Use custom/edited Supply challenge scenario for the TAS purposes providing said interface.

```lua
mod_gui = require "mod-gui"

if script.mod_name == "level" and script.level and script.level.level_name == "supply" then
    remote.add_interface("DunRaider-TAS-supply",
    { next_level = function(player_index)
            -- fake the "next level" button click event
            local player = game.get_player(player_index)
            local btn = mod_gui.get_button_flow(player).next_level
            if (not btn) or (not btn.enabled) then return end
            local event = {
                name=1,
                tick=game.tick,
                player_index=player_index,
                element=btn,
            }
            story_update(global.story, event, "")
        end,
    })
end
```

Thank you for your consideration and for developing and maintaining this tool.

**Comment by MortenTobiasNielsen** [comment]
Hi seky16. Thanks for your suggestion, it sounds like a good addition. I am not currently developing on the project, but maybe theis999 will have a look at it at some point. :) 

until then, It seems like you should be able to start your run without being able to go to the next level. You should be able to add the required items to a chest when you plan to press the button and "pretend" that the items no longer exists. This will allow you to get going and when the feature is added it should be easy to just add the "next level" step right after you insert the items into a box - you can add a comment in FTG to remember where you want to go the a new level.

**Comment by theis999** [comment]
I suspect option 3 is the easiest and fastest to work on. It is a relatively isolated task to re-create the scenario without the pop-up messages and provide a method for the TAS mod to progress the level. We also need to remove the next level button, as pressing that can only cause issues.

Changing the goals setup should be trivial, however we will also need a new step type for changing the level.

**Comment by seky16** [comment]
Yes, for now it's possible (with a little tweak to control.lua - can provide that) to work on this run. I suspect the "next level" steps will probably be used on the very end of the run. 

@theis999 Yeah, custom scenario is the easiest way to go now, but I'm not sure it's portable enough. Unless you bundle the custom scenario with the generated mod, no one else would be able to play the TAS themselves.

**Comment by MortenTobiasNielsen** [comment]
Sounds good. I guess we could change the Launch step to _Next_ when the goal is changed to Supply Challenge. 
In terms of the custom scenario I would expect that the entire thing will be bundled to a new scenario like it is done with the other goals (steelaxe, etc.) or isn't that possible @theis999?

**Comment by theis999** [comment]
In terms of GUI sure, but it'll have to be a different steptype for most purposes.

There are no real problems with including a scenario with a mod.
