### ISSUE TITLE
More undo

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-GUI-V2#350]
There are a few glaring omissions from the undo/redo system:

- Export template, from the template page
- Import steps, from step importer page
- Mark multiple rows for Force or Split

**Comment by theis999** [comment]
I have come to the conclusion, that current framework for undo is unwieldy. So i have been working a new framework that is more audit-like.

**Comment by MortenTobiasNielsen** [comment]
Well done Theis. Nice to see that you are still active. 👍

**Comment by theis999** [comment]
Thank you! The new way of handling undo is much easier to work with, to the point where using it to move rows was easier rather than the old code for moving rows.

**Comment by MortenTobiasNielsen** [comment]
I have used your version for a steelaxe run I am working on and unfortunately half the time I use undo it crashes the application.  😓 When using auto for recipes it provides the wrong items, but only for some of them e.g. Iron gear wheel (probably an array indexing issue).

**Comment by MortenTobiasNielsen** [comment]
I just remembered that adding a task to craft a lab for some reason doesn't work either. I can create some issues of you would like it in that format. :)

**Comment by theis999** [comment]
I uploaded a new version less than an hour ago which might fix some of the crashes you experienced. A refactor of scrolling to the redone steps caused some empty set issues.

I rarely add build steps manually, so issues with auto put could have crept into the code.

I wouldn't mind help in the QA department 😎

**Comment by MortenTobiasNielsen** [comment]
Nice, I will have look at the new version when I have the chance.

Do you record all the steps - even putting alle the items into e.g.
assemblers?

Understandable, it is cumbersome to do thorough testing. 😅

**Comment by theis999** [comment]
Indeed, but to be fair i don't use the software very much. So i don't have an intuitive sense of where everything is on the GUI.

You are free to post issues or message me on discord, if i understand the problem then i will fix it ;)
