### ISSUE TITLE
Disable intermediate walk steps

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-GUI-V2#351]
I have noticed that people are generally not happy with FTG adding intermediate walk steps, and applies the new Force modifier to almost every step.

As i see it, this leaves us with 3 options:
1. Implement a generator wide Force modifier
2. Improve the distance calculation further, to mitigate the problem
3. Allow intermediate steps to be skipped, if the step can be performed

Option 1 is obviously the easier of the three.

**Comment by MortenTobiasNielsen** [comment]
It does seem that the intermediate step doesn't provide as much value as it once did, given the advances in support tools. It once provided an "easy" way to know if you were approximately within range with a pretty good certainty, but today it is easier to enable the "interaction circle" in your mod. So it might be that we should have a "Distance calculations enabled" flag or something like that.
