### ISSUE TITLE
In-place Steps grid editor

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-GUI-V2#354]
WxGrid allows for in-place editor instead of having to: 
- Double click a step
- Change details using the details panel
- Click change step

Which requires many clicks and a lot of mouse movement.

There is a non-trivial issue of having to update both the gui, checking the input abides by the same rules as details panel & updating the real steps list.

**Comment by MortenTobiasNielsen** [comment]
I had a look at this some time back and came to the same conclusion - that it would be really hard to implement and therefore didn't choose to do it. It would be nice to have, but it is not that difficult to change a step and it is not something which is done multiple times a minutes. I therefore think that there are more value adding ways of spending your time, but it is your time. :)

**Comment by CasparPetch** [comment]
I would love this to be a feature. It is fairly often that I have to change many steps at once, eg 15 different put steps go from put 3 coal to put 5. Takes a rather unnecessary amount of time currently I would say

**Comment by MortenTobiasNielsen** [comment]
You would be able to do that by using the template feature. Specifically changing coal added to furnaces was one of the main reasons I created the possibility to add or multiply amounts in templates. It should take no more than 30 seconds when you have tried it a few times. 🙂

**Comment by CasparPetch** [comment]
Does that only work when the steps you want to edit are all consecutive?
But true, I didn't think of that tbh. thanks

**Comment by MortenTobiasNielsen** [comment]
It can give some problems if you have a lot of e.g. rotation steps included in a section, given that those will be affected aswell, but in general I find that there are relatively few steps which have amount, so normally it is relatively easy to change even a very large section without changing something else than what you need to change.

**Comment by CasparPetch** [comment]
Sure, I will keep it in mind next time that situation comes up, cheers

**Comment by theis999** [comment]
> I would love this to be a feature. It is fairly often that I have to change many steps at once, eg 15 different put steps go from put 3 coal to put 5. Takes a rather unnecessary amount of time currently I would say

I doubt i can manage to make a multi row change functionality, as known in excel or similar.
