### ISSUE TITLE
Button to copy a row instead of double click

### ISSUE THREAD

**Issue by CasparPetch** [MortenTobiasNielsen/Factorio-GUI-V2#360]
Now that double clicking in most cells will edit that cell rather than copy its entire row, the only way to copy a row is to double click the leftmost cell. I have always found copying rows to be a little cumbersome and now it is even more so. Perhaps a button that is clicked once at the left edge (where the row number lies) would be a good alternative. Additionally could add a hotkey (probably ctrl-C) to do it even faster.

**Comment by MortenTobiasNielsen** [comment]
Ohh yeah, that was also a reason why I didn't do the in row editing. A copy shortcut might be the way to go, now that it has been chosen to implement the in row editing.

**Comment by theis999** [comment]
That doesn't appear to be true. At least from my testing, double clicking works as well as it always has (which was never great). It might perhaps not be as obvious that it works, since there is more going on on the screen.

**Comment by MortenTobiasNielsen** [comment]
I guess it is one of those "perceived performance" things. 😅
