### ISSUE TITLE
Unset recipes

### ISSUE THREAD

**Issue by CasparPetch** [MortenTobiasNielsen/Factorio-GUI-V2#363]
Currently there is no way to return an assembler to the state it is in when it is first placed - without a recipe. The reason this would be useful is in the case of oil refineries: when you switch from basic oil processing to advanced oil processing, the 200 crude oil in the internal buffer is deleted. But if you switch to no recipe first, you get 100 crude pushed back into the connecting pipe. In a system where the amount produced by the pumpjacks is exactly equal (or a slight bit less) than the amount consumed by refineries, then there is a loss of production when the switch is made. Reference bug report I made: https://forums.factorio.com/viewtopic.php?f=7&t=107830&p=587923#p587923

**Comment by MortenTobiasNielsen** [comment]
Sounds like a good addition to make. 👍

**Comment by theis999** [comment]
Adding a "none" recipe should be easy enough. It just needs to be translated in lua into nil.
I am a bit worried about the complexity of transferring Null values around in the program.

**Comment by MortenTobiasNielsen** [comment]
Agreed. Sounds like a recipe for trouble to use null for this, so it should probably be None as a string and only at the point of setting the recipe in the game be translated to nil.
