### ISSUE TITLE
"wait for" with craft tasks wastes a crafting tick

### ISSUE THREAD

**Issue by CasparPetch** [MortenTobiasNielsen/Factorio-GUI-V2#364]
not sure if it is possible to fix or not but thought I'd flag it just in case

**Comment by theis999** [comment]
I am do not think you are correct. I believe crafting wastes a tick, regardless of "wait for".

I tested using a setup with 5 craft steps:
1. All 5 steps had wait for enabled
2. The first 4 steps had wait for disabled and the last step had wait for enabled

Both ended at the same tick.
